site_name: Fiware-Pep-Proxy
site_url: http://fiware-pep-proxy.readthedocs.org
repo_url: https://github.com/ging/fiware-pep-proxy
site_description: Pep Proxy Wilma Documentation
docs_dir: doc
site_dir: html
theme: readthedocs
extra_css: ["https://fiware.org/style/fiware_readthedocs.css"]
pages:
 - Home: index.md
 - 'User and Programmers Guide': user_guide.md
 - 'Installation and Administration Guide': admin_guide.md
google_analytics: ['UA-83727401-3', 'fiware-pep-proxy.readthedocs.io']
